apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hoshi
  name: hoshi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hoshi
  template:
    metadata:
      labels:
        app: hoshi
    spec:
      containers:
      - image: rotoku/hoshi:1.0.0
        name: hoshi
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hoshi
  labels:
    app: hoshi
    job: hoshi
spec:
  selector:
    app: hoshi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: tcp-app
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: hoshi-service-monitor
  labels:
    release: prometheus
    app: hoshi
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: hoshi
